# Generated by Django 4.2.11 on 2026-02-07 18:59

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import ide.models.build
import ide.models.dependency
import ide.utils
import ide.utils.whatsnew


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=ide.models.build.generate_uuid, max_length=36, validators=[django.core.validators.RegexValidator('^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$', message='Invalid UUID.')])),
                ('state', models.IntegerField(choices=[(1, 'Pending'), (2, 'Failed'), (3, 'Succeeded')], default=1)),
                ('started', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_modified', models.DateTimeField(auto_now_add=True)),
                ('project_type', models.CharField(choices=[('native', 'Pebble C SDK'), ('simplyjs', 'Simply.js'), ('pebblejs', 'Pebble.js (beta)'), ('package', 'Pebble Package'), ('rocky', 'Rocky.js')], default='native', max_length=10)),
                ('sdk_version', models.CharField(choices=[('2', 'SDK 2 (obsolete)'), ('3', 'SDK 4 beta')], default='2', max_length=6)),
                ('app_uuid', models.CharField(blank=True, default=ide.utils.generate_half_uuid, max_length=36, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$', message='Invalid UUID.')])),
                ('app_company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('app_short_name', models.CharField(blank=True, max_length=100, null=True)),
                ('app_long_name', models.CharField(blank=True, max_length=100, null=True)),
                ('app_version_label', models.CharField(blank=True, default='1.0', max_length=40, null=True)),
                ('app_is_watchface', models.BooleanField(default=False)),
                ('app_is_hidden', models.BooleanField(default=False)),
                ('app_is_shown_on_communication', models.BooleanField(default=False)),
                ('app_capabilities', models.CharField(blank=True, max_length=255, null=True)),
                ('app_keys', models.TextField(default='{}')),
                ('app_jshint', models.BooleanField(default=True)),
                ('app_platforms', models.TextField(blank=True, max_length=255, null=True)),
                ('app_modern_multi_js', models.BooleanField(default=True)),
                ('app_keywords', models.TextField(default='[]')),
                ('optimisation', models.CharField(choices=[('0', 'None'), ('1', 'Limited'), ('s', 'Prefer smaller'), ('2', 'Prefer faster'), ('3', 'Aggressive (faster, bigger)')], default='s', max_length=1)),
                ('github_repo', models.CharField(blank=True, max_length=100, null=True)),
                ('github_branch', models.CharField(blank=True, max_length=100, null=True)),
                ('github_last_sync', models.DateTimeField(blank=True, null=True)),
                ('github_last_commit', models.CharField(blank=True, max_length=40, null=True)),
                ('github_hook_uuid', models.CharField(blank=True, max_length=36, null=True)),
                ('github_hook_build', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_dependencies', models.ManyToManyField(to='ide.project')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResourceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[/a-zA-Z0-9_(). -]+$', message='Invalid filename.')])),
                ('kind', models.CharField(choices=[('raw', 'Binary blob'), ('bitmap', 'Bitmap Image'), ('png', '1-bit PNG'), ('png-trans', '1-bit PNG with transparency'), ('font', 'True-Type Font'), ('pbi', '1-bit Pebble image')], max_length=9)),
                ('is_menu_icon', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='ide.project')),
            ],
            options={
                'abstract': False,
                'unique_together': {('project', 'file_name')},
            },
        ),
        migrations.CreateModel(
            name='UserGithub',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='github', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('token', models.CharField(blank=True, max_length=50, null=True)),
                ('nonce', models.CharField(blank=True, max_length=36, null=True)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('avatar', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('autocomplete', models.IntegerField(choices=[(1, 'As-you-type'), (2, 'When pressing Ctrl-Space'), (3, 'Never')], default=1, verbose_name='Autocompletion')),
                ('keybinds', models.CharField(choices=[('default', 'Standard'), ('vim', 'vim-like'), ('emacs', 'emacs-like')], default='default', max_length=20, verbose_name='Keybinds')),
                ('theme', models.CharField(choices=[('cloudpebble', 'CloudPebble'), ('monokai', 'Monokai (Sublime Text)'), ('blackboard', 'Blackboard (TextMate)'), ('eclipse', 'Eclipse'), ('solarized light', 'Solarized (light)'), ('solarized dark', 'Solarized (dark)')], default='cloudpebble', max_length=50, verbose_name='Theme')),
                ('use_spaces', models.BooleanField(choices=[(True, 'Using spaces'), (False, 'Using tabs')], default=True, verbose_name='Indents')),
                ('tab_width', models.PositiveSmallIntegerField(default=2, verbose_name='Tab width')),
                ('accepted_terms', models.BooleanField(default=True)),
                ('whats_new', models.PositiveIntegerField(default=ide.utils.whatsnew.count_things)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateProject',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ide.project')),
                ('template_kind', models.IntegerField(choices=[(1, 'Template'), (2, 'SDK Demo')], db_index=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('ide.project',),
        ),
        migrations.CreateModel(
            name='ResourceIdentifier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^\\w+$', message='Invalid resource ID.')])),
                ('character_regex', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking', models.IntegerField(blank=True, null=True)),
                ('compatibility', models.CharField(blank=True, max_length=10, null=True)),
                ('target_platforms', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('memory_format', models.CharField(blank=True, choices=[('Smallest', 'Smallest'), ('SmallestPalette', 'Smallest Palette'), ('1Bit', '1-bit'), ('8Bit', '8-bit'), ('1BitPalette', '1-bit Palette'), ('2BitPalette', '2-bit Palette'), ('4BitPalette', '4-bit Palette')], max_length=15, null=True)),
                ('storage_format', models.CharField(blank=True, choices=[('pbi', '1 bit Pebble Image'), ('png', 'PNG')], max_length=3, null=True)),
                ('space_optimisation', models.CharField(blank=True, choices=[('storage', 'Storage'), ('memory', 'Memory')], max_length=7, null=True)),
                ('resource_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='ide.resourcefile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuildSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('total_size', models.IntegerField(blank=True, null=True)),
                ('binary_size', models.IntegerField(blank=True, null=True)),
                ('resource_size', models.IntegerField(blank=True, null=True)),
                ('worker_size', models.IntegerField(blank=True, null=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='ide.buildresult')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='buildresult',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='ide.project'),
        ),
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('folded_lines', models.TextField(default='[]')),
                ('file_name', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[/a-zA-Z0-9_.-]+\\.(c|h|js|json)$', message='Invalid file name.')])),
                ('target', models.CharField(choices=[('app', 'App'), ('pkjs', 'PebbleKit JS'), ('worker', 'Worker'), ('public', 'Public Header File'), ('common', 'Shared JS')], default='app', max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_files', to='ide.project')),
            ],
            options={
                'abstract': False,
                'unique_together': {('project', 'file_name', 'target')},
            },
        ),
        migrations.CreateModel(
            name='ResourceVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, max_length=50)),
                ('is_legacy', models.BooleanField(default=False)),
                ('resource_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='ide.resourcefile')),
            ],
            options={
                'abstract': False,
                'unique_together': {('resource_file', 'tags')},
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=2000, validators=[ide.models.dependency.validate_dependency_version])),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='ide.project')),
            ],
            options={
                'abstract': False,
                'unique_together': {('project', 'name')},
            },
        ),
    ]
