# Generated by Django 4.2.11 on 2026-02-09 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0002_add_alloy_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_dependencies',
            field=models.ManyToManyField(db_table='cloudpebble_project_dependencies', to='ide.project'),
        ),
        migrations.AlterModelTable(
            name='buildresult',
            table='cloudpebble_build_results',
        ),
        migrations.AlterModelTable(
            name='buildsize',
            table='cloudpebble_build_sizes',
        ),
        migrations.AlterModelTable(
            name='dependency',
            table='cloudpebble_dependencies',
        ),
        migrations.AlterModelTable(
            name='project',
            table='cloudpebble_projects',
        ),
        migrations.AlterModelTable(
            name='resourcefile',
            table='cloudpebble_resource_files',
        ),
        migrations.AlterModelTable(
            name='resourceidentifier',
            table='cloudpebble_resource_identifiers',
        ),
        migrations.AlterModelTable(
            name='resourcevariant',
            table='cloudpebble_resource_variants',
        ),
        migrations.AlterModelTable(
            name='sourcefile',
            table='cloudpebble_source_files',
        ),
        migrations.AlterModelTable(
            name='templateproject',
            table='cloudpebble_template_projects',
        ),
        migrations.AlterModelTable(
            name='usergithub',
            table='cloudpebble_user_github',
        ),
        migrations.AlterModelTable(
            name='usersettings',
            table='cloudpebble_user_settings',
        ),
    ]
