# Generated by Django 4.2.11 on 2026-03-31 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ide', '0008_publishedmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('native', 'Pebble C SDK'), ('simplyjs', 'Simply.js'), ('pebblejs', 'Pebble.js (beta)'), ('package', 'Pebble Package'), ('rocky', 'Rocky.js'), ('alloy', 'JavaScript SDK (beta)')], default='native', max_length=10),
        ),
        migrations.AlterField(
            model_name='publishedmedia',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^\\w+$', message='Invalid name.')]),
        ),
        migrations.AlterField(
            model_name='sourcefile',
            name='file_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[/a-zA-Z0-9_.-]+$', message='Invalid file name.')]),
        ),
    ]
